// src/components/AcceptTermsOfUse.vue
<template>
  <section class="AcceptTermsOfUse d-flex justify-content-center">
    <div class="form-check d-inline-block w-auto">
      <input
        id="terms-of-use"
        type="checkbox"
        class="form-check-input"
        :checked="checked"
        :disabled="disabled"
        @change="handleChange"
      />
      <label for="terms-of-use" class="form-check-label font-weight-bold">
        I HAVE READ and I AGREE to the Impresso Terms of Use.
      </label>
    </div>
  </section>
</template>

<script setup lang="ts">
interface AcceptTermsOfUseProps {
  disabled?: boolean
  checked?: boolean
  onChange?: (event: Event) => void
}

const props = withDefaults(defineProps<AcceptTermsOfUseProps>(), {
  disabled: false,
  checked: false,
  onChange: () => {
    console.log("AcceptTermsOfUse.onChange")
  },
})

const handleChange = (event: Event) => {
  props.onChange?.(event)
}
</script>

// src/components/AcceptTermsOfUse.tsx
import { Form } from "react-bootstrap"
import type { FC, ChangeEvent } from "react"

interface AcceptTermsOfUseProps {
  disabled?: boolean
  checked?: boolean
  onChange?: (event: ChangeEvent<HTMLInputElement>) => void
}

const AcceptTermsOfUse: FC<AcceptTermsOfUseProps> = ({
  disabled = false,
  checked = false,
  onChange = () => {
    console.log("AcceptTermsOfUse.onChange")
  },
}) => {
  return (
    <section className="AcceptTermsOfUse border-top mx-3 py-4 mt-0 w-100 d-flex justify-content-center">
      <Form.Check className="d-inline-block w-auto">
        <Form.Check.Input
          type="checkbox"
          id="terms-of-use"
          checked={checked}
          onChange={onChange}
          disabled={disabled}
        />
        <Form.Check.Label htmlFor="terms-of-use" className="font-weight-bold">
          I HAVE READ and I AGREE to the Impresso Terms of Use.
        </Form.Check.Label>
      </Form.Check>
    </section>
  )
}

export default AcceptTermsOfUse
